### ISSUE TITLE
missing definition of dierect-non-list-initialization

### ISSUE THREAD

**Issue by akrzemi1** [cplusplus/fundamentals-ts#10]
The standardese of N3672 also added the following sub-clause:

17.3.11 [defns.direct-non-list-init]
dierect-non-list-initialization
A direct-initialization that is not list-initialization.

This must have got lost during the incorporation into the TS. The number 17.3.11 is obviously wrong now.

**Comment by akrzemi1** [comment]
For some background, this definition is only used by Optional standardese, but the feedback I got (can't remember from whom) was that it is generally useful and should be added into Library Introduction clause. Now that Optional is heading for a TS, I am not sure where the definition should end up.

**Comment by jyasskin** [comment]
I think the Fundamentals TS is a reasonable place for this definition, until it gets added to the main standard.
