### ISSUE TITLE
inconsistent namespaces

### ISSUE THREAD

**Issue by jwakely** [cplusplus/fundamentals-ts#12]
According to N3804 `any` is in `std::experimental::any_v1`

`optional`, `string_view` and `search` are in `std::experimental::fundamentals_v1`

**Comment by jyasskin** [comment]
Yeah, we pointed that out in the `any` review, but it doesn't seem to have gotten fixed by the paper that actually got voted in. I'm happy to treat this type of problem as editorial though, and will fix it when I add the paper to the WD.

**Comment by Beman** [comment]
On Wed, Feb 19, 2014 at 1:55 PM, Jeffrey Yasskin
notifications@github.comwrote:

> Yeah, we pointed that out in the any review, but it doesn't seem to have
> gotten fixed by the paper that actually got voted in. I'm happy to treat
> this type of problem as editorial though, and will fix it when I add the
> paper to the WD.
> 
> Here are my notes on editorial fixes needed for  any.
- Change /clause/section/
- Fix namespace _v1  (I.E. the problem Jonathan noted.)
- Strike std:: where inappropriate.
- For any operator=, change:

_Effects:_ any(rhs).swap(*this), however, no effects if an exception is
thrown.

to

_Effects:_ any(rhs).swap(*this). No effects if an exception is thrown.

--Beman
