### ISSUE TITLE
Missing code font for "upstream"

### ISSUE THREAD

**Issue by Dani-Hub** [cplusplus/fundamentals-ts#23]
The wording in  [memory.resource.pool.ctor] p3 refers to parameter "upstream" but misses to set it in code font ("from _upstream_ whenever")

**Comment by Dani-Hub** [comment]
The same problem exists for  [memory.resource.monotonic.buffer.overview] p1 b3 ("from an _upstream_ memory")

**Comment by jyasskin** [comment]
Re memory.resource.monotonic.buffer.overview, that looks like a definition, but "upstream allocator" was already defined in [pool.resource.overview]. I guess these are separate sections, and the term is slightly different, so it makes some sense to make it italic here. I'll do that, but we may want to unify the definition of "upstream" at a higher level.
