### ISSUE TITLE
Missing table title ( [memory.type.erased.allocator])

### ISSUE THREAD

**Issue by Dani-Hub** [cplusplus/fundamentals-ts#30]
The table title ("Computed <tt>memory_resource</tt> for type-erased allocator") is missing

**Comment by jyasskin** [comment]
I see it as "Table 9 — Computed `memory_resource` for type-erased allocator" at http://cplusplus.github.io/fundamentals-ts/fundamentals-ts.html#tab:memory.resource.type.erased.allocator. Tentatively closing, but please reopen if I've missed something.
