### ISSUE TITLE
Further missing table titles 

### ISSUE THREAD

**Issue by Dani-Hub** [cplusplus/fundamentals-ts#32]
The following tables are also missing their titles:
 [general.namespaces]:
Table 1

 [general.feature.test]:
Table 2

 [meta.trans.other]
Table 3

[string.view.cons]:
Table 4
Table 5
Table 6

 [string.view.ops]:
Table 7

 [string.view.comparison]
Table 8

**Comment by jyasskin** [comment]
I'm now thinking this has something to do with the way I'm generating the table number as part of the caption. I wind up with `<table><caption>Table 1 — <caption>title</caption></caption>` which confuses Firefox, at least. I'll poke at it some more.
