### ISSUE TITLE
Missing wording for optional's value_or

### ISSUE THREAD

**Issue by Dani-Hub** [cplusplus/fundamentals-ts#35]
According to n3793, the remarks element of  [optional.object.observe] p23 should be worded the following way:

Remarks: If both constructors of T which could be selected are constexpr constructors, this function shall be a constexpr function.

This seems not be properly applied, instead the wording corresponds to a previous version of the proposal

**Comment by jyasskin** [comment]
In Issaquah the LWG concluded that this particular change was incorrect:

["Jonathan: The change where we changed "selected constructor of `T` is a `constexpr`" to "If both constructors..." is in fact wrong, and should be reverted.](http://wiki.edg.com/twiki/bin/view/Wg21issaquah/N3793)

We didn't get an updated paper with that change, so I'm not sure what the proper procedure is here. By omitting the change today, we don't have to undo it in Rapperswil, but the committee did vote in the whole paper, mistakes and all.

**Comment by Dani-Hub** [comment]
2014-03-03 0:02 GMT+01:00 Jeffrey Yasskin notifications@github.com:

> In Issaquah the LWG concluded that this particular change was incorrect:
> 
> "Jonathan: The change where we changed "selected constructor of T is a
> constexpr" to "If both constructors..." is in fact wrong, and should be
> reverted. http://wiki.edg.com/twiki/bin/view/Wg21issaquah/N3793
> 
> We didn't get an updated paper with that change, so I'm not sure what the
> proper procedure is here. By omitting the change today, we don't have to
> undo it in Rapperswil, but the committee did vote in the whole paper,
> mistakes and all.

Thanks for the update. Personally I have no complains, but we need to be
sure that we don't conflict with the formalities. Given that I see no
change request for this on the Formal Motions page I suspect the right way
is to apply the wording as suggested for the motion and than to open an
issue to fix it.
