### ISSUE TITLE
reword throw spec of boyer-moore searchers

### ISSUE THREAD

**Issue by jwakely** [cplusplus/fundamentals-ts#43]
In Urbana LWG suggested rewording 4.3.2/5 and 4.3.3/5 so that

> "May throw bad_alloc if cannot allocate additional memory for internal data structures needed."  

would become something like:

> "May throw bad_alloc if additional memory needed for internal data structures cannot be allocated."

**Comment by jwakely** [comment]
Did you fix both occurrences or just one?  (Sorry, unable to check myself right now)

**Comment by jyasskin** [comment]
Whoops, just one. Second fix coming up.
