### ISSUE TITLE
Has optional::get be removed accidently?

### ISSUE THREAD

**Issue by viboes** [cplusplus/fundamentals-ts#44]

**Comment by jyasskin** [comment]
Nope, none of [N3672](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2013/n3672.html), [N3793](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2013/n3793), nor [N4078](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2014/n4078.html) propose an `optional::get()` method. http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2013/n3672.html#comparison_with_boost explicitly mentions skipping `get()` and `get_ptr()`. File a bug at issues.isocpp.org for feature requests.
