### ISSUE TITLE
Shouldn't any_cast return by reference as std::get() and optional::value do? 

### ISSUE THREAD

**Issue by viboes** [cplusplus/fundamentals-ts#45]
This would improve the efficiency of the access.

**Comment by jwakely** [comment]
If you want a reference use `any_cast<X&>(a)` but if you want a value use `any_cast<X>(a)`

This matches the behaviour of `static_cast` etc.

**Comment by viboes** [comment]
does `any_cast<X&&>(f())` work?

**Comment by jwakely** [comment]
The spec seems clear:
https://rawgit.com/cplusplus/fundamentals-ts/v1/fundamentals-ts.html#any.nonmembers

Move from an `any` using `std::move(any_cast<X&>(f()))`

Anyway, this is not editorial so doesn't belong here.
