### ISSUE TITLE
Suspicious "cv-qualified void"

### ISSUE THREAD

**Issue by cpplearner** [cplusplus/fundamentals-ts#51]
N4480 8.2.1.2[memory.smartptr.shared.obs]p6 reads

> Remarks: When `T` is an array type or cv-qualified `void`, it is unspecified whether this member function is declared. If it is declared, it is unspecified what its return type is, except that the declaration (although not necessarily the definition) of the function shall be well formed.

The phrase "cv-qualified `void`" seems to imply that if `T` is cv-unqualified (plain) `void`, then this remark doesn't apply. I wonder whether this is the intent.

**Comment by jwakely** [comment]
We should check the LWG minutes (from Issaquah, I think) to see if we discussed it. I think the intent is "(possible cv-qualified) `void`"

**Comment by jyasskin** [comment]
I don't see it mentioned in http://wiki.edg.com/twiki/bin/view/Wg21issaquah/LibraryWorkingGroup. I'll file a library issue.

**Comment by jyasskin** [comment]
Filed http://cplusplus.github.io/LWG/lwg-active.html#2500. Thanks for the report.
