### ISSUE TITLE
Editorial nit

### ISSUE THREAD

**Issue by AlisdairM** [cplusplus/fundamentals-ts#59]
In the current working paper, N4529, Fundamentals 1 and 2 are merged.  The end result is that the <experimental/memory> header specification is now split between 8.1, 8.2, and 8.12.  That last clause should move up to be adjacent to the other <memory> edits.

It is not clear that 8.3 affects <memory> or <memory_resource>.  As written, I would suggest swapping the order of 8.3 and 8.4 as well.

**Comment by tkoeppe** [comment]
Fixed by effc031cee33aa9be9112cae7d1b81e7c4d5e83b.
