### ISSUE TITLE
Redondant Remark:  this function shall be a constexpr function.

### ISSUE THREAD

**Issue by viboes** [cplusplus/fundamentals-ts#6]
I don't see the need of adding the

  Remarks:      this function shall be a constexpr function. 

when the function is already declared constexpr.

**Comment by villevoutilainen** [comment]
Well, not all instantiations of function templates declared constexpr are actually constexpr - the intent of the wording here is that all instantiations of this 'temploid' do have to be constexpr.

**Comment by jyasskin** [comment]
@villevoutilainen is right, but it's worded wrong. C++11[dcl.constexpr]p2 says 

> A constexpr specifier used in the declaration of a function that is not a constructor declares that function to be a _constexpr function_. Similarly, a constexpr specifier used in a constructor declaration declares that constructor to be a _constexpr constructor_.

We need to follow Daniel's proposed resolution to http://cplusplus.github.io/LWG/lwg-active.html#2289 instead.

**Comment by jyasskin** [comment]
Thinking about this a bit more, the state of art in the C++ working draft is "shall be a constexpr constructor". Once LWG 2289 is accepted, I'll propagate its wording change here as an editorial issue.

**Comment by tkoeppe** [comment]
I think this is moot now; this wording no longer seems to appear in the TS.
