### ISSUE TITLE
Remove intensifiers from the allocators sections

### ISSUE THREAD

**Issue by jyasskin** [cplusplus/fundamentals-ts#65]
I've gotten a complaint that the allocators sections are full of meaningless intensifiers like "very". We should go through it and make sure the wording is just factual.

**Comment by sigfpe** [comment]
Agreed.-------- Original message --------From: Jeffrey Yasskin notifications@github.com Date: 10/16/2015  11:08 PM  (GMT-08:00) To: cplusplus/fundamentals-ts fundamentals-ts@noreply.github.com Subject: [fundamentals-ts] Remove intensifiers from the allocators sections
  (#65) 
I've gotten a complaint that the allocators sections are full of meaningless intensifiers like "very". We should go through it and make sure the wording is just factual.

**Comment by tkoeppe** [comment]
I think this is moot, no intensive sections remain in v3.
