### ISSUE TITLE
Use ins/del markers where we duplicate the standard

### ISSUE THREAD

**Issue by geoffromer** [cplusplus/fundamentals-ts#69]
Anywhere we duplicate text from the standard, we should use ins/del markers to mark any changes. This matches the practice of other TS's, and greatly simplifies the work of incorporating parts of the Fundamentals TS back into the standard. [memory.smartptr.shared.cast] is one known case where we don't do that; there may be others.

**Comment by tkoeppe** [comment]
I believe we're doing that now; most of the original culprits have been merged since.
