### ISSUE TITLE
Add cross-references to [alg.random.sample]

### ISSUE THREAD

**Issue by geoffromer** [cplusplus/fundamentals-ts#72]
We should add cross-references to [alg.random.sample], as described in https://github.com/cplusplus/draft/issues/696 (and our resolution should match the resolution of that issue).

**Comment by geoffromer** [comment]
We should also add cross references as discussed in https://github.com/cplusplus/draft/issues/697

**Comment by tkoeppe** [comment]
alg.random.sample is no longer part of the TS, after having been merged, so this is now moot.
