### ISSUE TITLE
What would be the reason to make scope_exit (also scope_success, scope_fail) to be move constructable?

### ISSUE THREAD

**Issue by Logiquo** [cplusplus/fundamentals-ts#81]
For me, it kind of doesn't make sense. 

1. I cannot consider the use case for this. 

2. it can introduce some dangerous behaviour, i.e.

```C++
auto function() {
    int x;
    scope_exit s = [&]() { x -= 1; }
    return s;
}
```

which can be entirely avoided if we do not allow move construct.

3. If we do not allow move construct, implementation can have less cost as we can now use the reference of exit function instead of the copy of the exit function.

4. Some other similar `class` currently in standard, i.e. `lock_guard` does not permit move construct.

**Comment by tkoeppe** [comment]
This issue tracker is for *editorial* issues only. For technical discussion, please contact either the paper authors or the committee (https://isocpp.org/std/submit-issue).
